# Generated by Django 5.1.5 on 2025-08-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cart_auto_save',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('CAD', 'CAD (C$)')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch')], default='en', max_length=2),
        ),
    ]
